openapi: 3.0.0
info:
  title: ログイン
  version: '1.0'
  description: ログイン
  contact:
    name: FCApp
servers:
  - url: 'http://localhost:3000/api'
    description: Test Server
paths:
  /login:
    post:
      summary: ログイン
      tags:
        - Authenticate
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: APIアクセストークン
                  client:
                    $ref: '#/components/schemas/Client-loggedin'
                  status:
                    type: string
                  first_survey_url:
                    type: string
                    description: 初回アンケートURL
                required:
                  - access_token
                  - client
                  - status
              examples:
                example:
                  value:
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hc29iaS50ZXN0XC9hcGlcL2FkbWluXC9sb2dpbiIsImlhdCI6MTU3MjMzMDUwNSwiZXhwIjoxNTcyMzM0MTA1LCJuYmYiOjE1NzIzMzA1MDUsImp0aSI6IlBzYmxkTWtPVWduVTdrSGYiLCJzdWIiOjIsInBydiI6ImNlNjM2MDFjMDc0Yzc5ZWIzM2Y1YjI5YWU2NGRmOTUxYzJjYTRhZjEifQ.wpEmWqF_BasbY0
                    client:
                      id: 1
                      login_id: User
                      password: $2y$10$DHcchiEiAOvIbwmFunVH2.aYB4IxXbZzFeNcl0f267VuOhfxUI.ju
                      email: tyamada@example.com
                      full_name: 山田 太郎
                    first_survey_url: 'http://localhost:8080/api/first_survey/1'
                    status: success
                example-No first survey:
                  value:
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hc29iaS50ZXN0XC9hcGlcL2FkbWluXC9sb2dpbiIsImlhdCI6MTU3MjMzMDUwNSwiZXhwIjoxNTcyMzM0MTA1LCJuYmYiOjE1NzIzMzA1MDUsImp0aSI6IlBzYmxkTWtPVWduVTdrSGYiLCJzdWIiOjIsInBydiI6ImNlNjM2MDFjMDc0Yzc5ZWIzM2Y1YjI5YWU2NGRmOTUxYzJjYTRhZjEifQ.wpEmWqF_BasbY0
                    client:
                      id: 1
                      login_id: User
                      password: $2y$10$DHcchiEiAOvIbwmFunVH2.aYB4IxXbZzFeNcl0f267VuOhfxUI.ju
                      email: tyamada@example.com
                      full_name: 山田 太郎
                    first_survey_url: ''
                    status: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
                required:
                  - status
                  - error
              examples:
                example:
                  value:
                    error: Unauthorized
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  description: ログインID
                  maxLength: 20
                password:
                  type: string
                  description: パスワード
                  format: password
                  maxLength: 20
                device_type:
                  type: string
                  description: デバイス種別(iOS/Android)
                device_token:
                  type: string
                  description: デバイストークン
              required:
                - login_id
                - password
            examples:
              example:
                value:
                  login_id: User
                  password: Passw0rd
                  device_type: iOS
                  device_token: token
        description: ''
      description: ログイン
components:
  schemas:
    Client-loggedin:
      title: 顧客情報
      type: object
      description: ログインした顧客情報モデル
      properties:
        id:
          type: integer
          description: 顧客ID
        login_id:
          type: string
          description: ログインID
        password:
          type: string
          description: 暗号化されたパスワード
        email:
          type: string
          description: メールアドレス
        full_name:
          type: string
          description: 名前
      required:
        - id
        - login_id
        - password
        - email
        - full_name
      x-examples:
        example:
          value:
            id: 1
            login_id: user
            password: $2y$10$DHcchiEiAOvIbwmFunVH2.aYB4IxXbZzFeNcl0f267VuOhfxUI.ju
            email: tyamada@example.com
            full_name: 山田 太郎
